# kbuild trick to avoid linker error. Can be omitted if a module is built.
obj-m := khello.o
#khello-objs := khello.o


# List of programs to build
hostprogs-y := hello

# Tell kbuild to always build the programs
always := $(hostprogs-y)

HOSTCFLAGS_hello.o += -I$(objtree)/usr/include
