# kbuild trick to avoid linker error. Can be omitted if a module is built.
obj-m := sample_nl.o

# List of programs to build
hostprogs-y := server client server_nl

# Tell kbuild to always build the programs
always := $(hostprogs-y)

HOST_LOADLIBES += -lnl
HOSTCFLAGS_client.o +=  -g -I$(objtree)/usr/include -I/usr/include
HOSTCFLAGS_server_nl.o +=  -g -I$(objtree)/usr/include
HOSTCFLAGS_server.o += -g -I$(objtree)/usr/include
